title: Kien Tran
logo: /assests/img/doremon.jpg
description: Simple porfolio
show_downloads: true
theme: jekyll-theme-minimal
social_links:
  linkedin: https://www.linkedin.com/in/kien-tran-trung/
  github: https://github.com/Crimrose